/* Generated by re2c 1.0.1 on Wed Dec 12 20:46:26 2018 */
#include "Parser.ih"

#include "poolc/parser/PoolParser.hpp"

int Parser::makeClass() { return CLASS; }
int Parser::makeExtends() { return EXTENDS; }
int Parser::makeLocal() { return LOCAL; }
int Parser::makeGlobal() { return GLOBAL; }
int Parser::makeAbstract() { return ABSTRACT; }
int Parser::makeNaked() { return NAKED; }

int Parser::makeID(String & identifier) {
    d_val__.u_string = &identifier;
    return ID;
}

int Parser::makeString(String & identifier) {
    d_val__.u_string = &identifier;
    return STRING;
}

int Parser::makeNumber(long value) {
    d_val__.u_number = value;
    return NUMBER;
}

int Parser::lex()
{
    return driver.lex(*this);
}

void Parser::error()
{
    driver.error("Syntax error");
}

void Parser::exceptionHandler(std::exception const &exc)         
{
    if (driver.error(exc.what())) throw;
}
